<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.129" timestamp="2024-06-09T16:14:24.018119" hostname="LAPTOP-9819MJD3"><testcase classname="test_example" name="test_addition" time="0.002" /><testcase classname="test_example" name="test_subtraction" time="0.001" /><testcase classname="test_example" name="test_division" time="0.001" /><testcase classname="test_example" name="test_failure" time="0.001"><failure message="assert (1 + 1) == 3">def test_failure():
    
&gt;      assert 1 + 1 == 3
E      assert (1 + 1) == 3

test_example.py:15: AssertionError</failure></testcase></testsuite></testsuites>